### ISSUE TITLE
Compile repository locally

### ISSUE THREAD

**Issue by ail3ngrimaldi** [virto-network/virto-app#22]
@b-avb need some help here 😵‍💫

**Comment by b-avb** [comment]
What happened? Some log?

**Comment by olanod** [comment]
@ail3ngrimaldi With the latest diouxus cli I can build the project(`dx serve`) @b-avb has work on `develop` branch, have you tried compiling from that branch?

**Comment by ail3ngrimaldi** [comment]
Yes, I've done that and it shows me this:

![image](https://github.com/virto-network/fido/assets/63558201/3967ff35-33b0-426e-b393-7761fb63d48f)

from there I don't know how to continue.
